const express = require('express')
const router = express.Router()
const postCreationPhoto = require('./../middlewares/postCreationPhoto')
const postDeletion = require('./../middlewares/postDeletion')
const postCreationInfo = require('./../middlewares/postCreationInfo')
const postDisplay = require('./../middlewares/postDisplay')
const postFeedUser = require('./../middlewares/postFeedUser')
const postListUser = require('./../middlewares/postListUser')
const postLike = require('./../middlewares/postLike')
const postFavorite = require('./../middlewares/postFavorite')
const postListFavorite = require('./../middlewares/postListFavorite')
const postListBest = require('./../middlewares/postListBest')
const postViewRegistration = require('./../middlewares/postViewRegistration')
const postDiscover = require('./../middlewares/postDiscover')
const postSearch = require('./../middlewares/postSearch')
const postListTag = require('./../middlewares/postListTag')
const postSetPhotoAlt = require('./../middlewares/postSetPhotoAlt')

router.get('/favorite/:username/:page', postListFavorite)
router.get('/user/:username/:page', postListUser)
router.get('/feed/:page', postFeedUser)
router.post('/photo/:mode', postCreationPhoto)
router.post('/alt', postSetPhotoAlt)
router.get('/discover/:page', postDiscover)
router.get('/best/:page', postListBest)
router.post('/tag/:page', postListTag)
router.get('/search', postSearch)
router.post('/info', postCreationInfo)
router.post('/like', postLike)
router.post('/view', postViewRegistration)
router.post('/favorite', postFavorite)
router.get('/:publicId', postDisplay)
router.delete('', postDeletion)

module.exports = router